name: polec
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+6
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: 3.0.0
  bloc: 8.1.0
  bloc_concurrency: 0.2.0
  country_code_picker: 2.0.2
  cupertino_icons: 1.0.5
  equatable: 2.0.5
  fl_country_code_picker: 0.0.4
  flash: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_launcher_icons: 0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_map: 3.0.0
  flutter_svg: 1.1.5
  freezed: 2.1.0
  freezed_annotation: 2.1.0
  get_it: 7.2.0
  go_router: 5.0.2
  injectable: 1.5.3
  intl: 0.17.0
  json_annotation: 4.7.0
  json_serializable: 6.5.4
  meta: 1.8.0
  motion_toast: 2.6.4
  provider: 6.0.4
  shared_preferences: 2.0.15
  syncfusion_flutter_charts: 20.3.52
  #Flutter map
  geolocator: 9.0.2
  location: 4.4.0
  stream_transform: 2.1.0
  path_drawing: 1.0.1
  mask_text_input_formatter: 2.4.0

dev_dependencies:
  bloc_test: 9.1.0
  build_runner: 2.2.1
  flutter_native_splash: 2.2.9
  flutter_test:
    sdk: flutter
  go_router_builder: 1.0.10
  mocktail: 0.3.0
  very_good_analysis: 3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fake_images/
    - assets/launcher_icon/
    - assets/journal.json
    - assets/categories.json
    - assets/recommended.json
    - assets/by-id.json
    - assets/near.json
    - assets/me.json
    - assets/favourites.json

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Bold.ttf

